language: julia

os:
  - osx
  - linux

julia:
  - release
  
notifications:
  email: false
 
before_install:
   sudo: required
   - julia -e 'Pkg.add("MAT"); Pkg.build("HDF5"); Pkg.build("MAT");'
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/jInv.jl","jInv"); Pkg.build("jInv");'
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/FactoredEikonalFastMarching.jl","FactoredEikonalFastMarching"); Pkg.build("FactoredEikonalFastMarching");'
   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("EikonalInv"); Pkg.test("EikonalInv"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("EikonalInv")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
